spring.application.name=mini-s3
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_s3
spring.datasource.username=postgres
spring.datasource.password=km
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Allow large file uploads (up to 500MB)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# Storage nodes
storage.nodes.list[0].id=node-1
storage.nodes.list[0].host=localhost
storage.nodes.list[0].port=9001

storage.nodes.list[1].id=node-2
storage.nodes.list[1].host=localhost
storage.nodes.list[1].port=9002

storage.nodes.list[2].id=node-3
storage.nodes.list[2].host=localhost
storage.nodes.list[2].port=9003
